test-outputs: test-outputs.c
	gcc -o test-outputs test-outputs.c -liobb

test-inputs: test-inputs.c
	gcc -o test-inputs test-inputs.c -liobb

all: test-outputs test-inputs

clean:
	rm -rf test-inputs test-outputs

